AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless Favorites Service

Parameters:
  Environment:
    Type: String
    Default: dev
  RetentionInDays:
    Type: Number
    Default: 7
    Description: CloudWatch Logs retention period for Lambda functions

Resources:
  AddFavoriteLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      MemorySize: 3072
      Handler: com.drissamri.favorites.AddFavoriteLambda::handleRequest
      CodeUri: target/lambda.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FavoritesTable
      Tracing: Active
      Timeout: 30
      Layers:
        - arn:aws:lambda:eu-west-1:254067382080:layer:splunk-lambda-extension:1
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          FAVORITE_TABLE: !Ref FavoritesTable
          OTEL_INSTRUMENTATION_AWS_LAMBDA_HANDLER: com.drissamri.favorites.AddFavoriteLambda::handleRequest"
          OTEL_LAMBDA_HANDLER: com.drissamri.favorites.AddFavoriteLambda::handleRequest"
          SPLUNK_ACCESS_TOKEN: 4s8o3Q-WXuX-ioNT6A4WHA
          SPLUNK_REALM: eu0
          FAST_INGEST: true

      Events:
        addFavorite:
          Type: HttpApi
          Properties:
            Path: /favorites
            Method: POST
            PayloadFormatVersion: "2.0"

  AddFavoriteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AddFavoriteLambda}"
      RetentionInDays: !Ref RetentionInDays

  FavoritesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  AddFavoriteApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/favorites"