AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless Favorites Service

Parameters:
  Environment:
    Type: String
    Default: dev
  RetentionInDays:
    Type: Number
    Default: 7
    Description: CloudWatch Logs retention period for Lambda functions

Resources:
  AddFavoriteLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      MemorySize: 3072
      Handler: com.drissamri.favorites.AddFavoriteLambda::handleRequest
      CodeUri: target/lambda.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FavoritesTable
      Tracing: Active
      Timeout: 30
      Layers:
        - arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-java-wrapper-ver-1-5-0:2
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-proxy-handler
          ENVIRONMENT: !Ref Environment
          FAVORITE_TABLE: !Ref FavoritesTable

      Events:
        addFavorite:
          Type: Api
          Properties:
            Path: /favorites
            Method: POST

  AddFavoriteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AddFavoriteLambda}"
      RetentionInDays: !Ref RetentionInDays

  FavoritesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  AddFavoriteApiEndpoint:
    Description: "REST API endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/favorites"